# Generated by Django 4.2 on 2023-05-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='auctions.comment'),
        ),
    ]
