# Generated by Django 4.2 on 2023-05-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_bid_user_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('ART', 'Art'), ('BIKES', 'Bikes'), ('CARS', 'Cars'), ('CLOTHES', 'Clothes'), ('COMPUTERS', 'Computers'), ('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('HOME & GARDEN', 'Home & Garden'), ('JEWELRY', 'Jewelry'), ('MUSIC', 'Music'), ('OFFICE & SCHOOL SUPPLIES', 'Office & School Supplies'), ('SPORTS & OUTDOORS', 'Sports & Outdoors'), ('TOYS & GAMES', 'Toys & Games'), ('TRAVEL', 'Travel'), ('OTHER', 'Other')], default='OTHER', max_length=25),
        ),
    ]
